export default {
  ITEM_CREATE: 'ITEM_CREATE',
  ITEM_UPDATE_STATUS_ONE: 'ITEM_UPDATE_STATUS_ONE',
  ITEM_UPDATE_NAME: 'ITEM_UPDATE_NAME',
  ITEM_DELETE_ONE: 'ITEM_DELETE_ONE',
  ITEM_DELETE_DONE: 'ITEM_DELETE_DONE',
  SET_FILTER: 'SET_FILTER',
  SAGA_ITEM_CREATED: 'SAGA_ITEM_CREATED',
  SAGA_ITEM_UPDATED: 'SAGA_ITEMS_UPDATED',
  SAGA_ITEM_DELETED: 'SAGA_ITEMS_DELETED',
  SAGA_DONE_DELETED: 'SAGA_DONE_DELETED',
  STORAGE_UPDATED: 'STORAGE_UPDATED',
}
