export default {
  ITEM_APPEND_ONE: 'ITEM_APPEND_ONE',
  ITEM_UPDATE_STATUS_ONE: 'ITEM_UPDATE_STATUS_ONE',
  ITEM_UPDATE_LABEL_ONE: 'ITEM_UPDATE_LABEL_ONE',
  ITEM_DELETE_ONE: 'ITEM_DELETE_ONE',
  ITEM_DELETE_DONE: 'ITEM_DELETE_DONE',
  SET_FILTER: 'SET_FILTER',
  SAGA_ITEM_APPENDED: 'SAGA_ITEM_APPENDED',
  SAGA_ITEM_UPDATED: 'SAGA_ITEMS_UPDATED',
  SAGA_ITEMS_DELETED: 'SAGA_ITEMS_DELETED',
  SAGA_FILTER_SET: 'SAGA_FILTER_SET',
  STORAGE_UPDATED: 'STORAGE_UPDATED',
  ITEM_TOGGLE_EDIT: 'ITEM_TOGGLE_EDIT',
}
