export default {
    ITEM_APPEND_ONE: "ITEM_APPEND_ONE",
    ITEM_UPDATE_STATUS_ONE: "ITEM_UPDATE_STATUS_ONE",
    ITEM_DELETE_ONE: "ITEM_DELETE_ONE",
    ITEM_DELETE_DONE: "ITEM_DELETE_DONE",
    SET_FILTER: "SET_FILTER",
    STORAGE_UPDATED: "STORAGE_UPDATED"
}