export default {
    ITEM_APPEND_ONE: "ITEM_APPEND_ONE",
    ITEM_UPDATE_STATUS_ONE: "ITEM_UPDATE_STATUS_ONE",
    ITEM_UPDATE_LABEL_ONE: "ITEM_UPDATE_LABEL_ONE",
    ITEM_DELETE_ONE: "ITEM_DELETE_ONE",
    ITEM_DELETE_DONE: "ITEM_DELETE_DONE",
    SET_FILTER: "SET_FILTER",
    STORAGE_ITEMS_UPDATED: "STORAGE_ITEMS_UPDATED",
    STORAGE_FILTER_UPDATED: "STORAGE_FILTER_UPDATED",
    ITEM_TOGGLE_EDIT: "ITEM_TOGGLE_EDIT"
}